
export const villas = [
    {
      id: 1,
      name: "Villa Luna",
      location: "Greece",
      category: "Mountains",
      guests: 11,
      bedrooms: 6,
      bathrooms: 10,
      squareMeter: "400",
      rating: 4.7,
      image: "https://imgs.search.brave.com/31vU_NDzc9zQgsaGNg2TK9_3Oe2YRNEWYHflToVKzzY/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9yZXMu/Y2xvdWRpbmFyeS5j/b20vbHV4dXJ5cC9p/bWFnZXMvd18xMjgw/LGNfbGltaXQsZl9h/dXRvLHFfYXV0by95/ZmVkanR3amlhazUz/cTNka2ZhcC84MzAt/cGljYWNoby1sbi0x.jpeg",
      dailyRent: "240",
    },
    {
      id: 2,
      name: "Villa Tosco",
      location: "Italy",
      category: "Mountains",
      guests: 8,
      bedrooms: 8,
      bathrooms: 12,
      squareMeter: "450",
      rating: 4.4,
      image: "https://imgs.search.brave.com/PRf8cf8iQeFpSzDpmaovS0bzB0sbdyGs5g-ZcjqS0no/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y2FzYWRlY2FtcG8u/Y29tLmRvL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDE5LzA1L0NW/LTVCRFJNLVZpbGxh/LUdyYXktMi0xMzUw/eDc2MC03Njh4NDMy/LmpwZw",
      dailyRent: "300",
    },
    {
      id: 3,
      name: "Aphrodite",
      location: "Greece",
      category: "Seaside",
      guests: 12,
      bedrooms: 6,
      bathrooms: 6,
      squareMeter: "500",
      rating: 4.9,
      image: "https://imgs.search.brave.com/xSPaXJMCuYApgEZ1qN9dzfzkOcsNSvxcM5jNuqQ94bg/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS1jZG4udHJpcGFk/dmlzb3IuY29tL21l/ZGlhL3ZyLXNwbGlj/ZS1qLzAyLzBkL2Yw/LzU1LmpwZw",
      dailyRent: "200",
    },
    {
      id: 4,
      name: "Villa Makarska",
      location: "Italy",
      category: "Mountains",
      guests: 12,
      bedrooms: 15,
      bathrooms: 20,
      squareMeter: "750",
      rating: 5.0,
      image: "https://imgs.search.brave.com/3roBJjiNvlfGj4kstzF2QE_tCLnKdHI2NcaGXNIXSXo/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tYWth/cnNrYS10b3VyaXN0/aWsuY29tL3dwLWNv/bnRlbnQvdXBsb2Fk/cy8yMDIyLzA1L1Zp/bGxhLU1vbmlhLU1v/bmlhLTQ0LTc0MHg2/NjAuanBn",
      dailyRent: "260",
    },
    {
      id: 5,
      name: "Villa Boxane",
      location: "Greece",
      category: "Mountains",
      guests: 4,
      bedrooms: 5,
      bathrooms: 6,
      squareMeter: "275",
      rating: 4.0,
      image: "https://imgs.search.brave.com/MVfaO56v-Z_LcVcxKRha1tNJgnBcmDPtgSo23tC_uPI/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly91cGxv/YWQud2lraW1lZGlh/Lm9yZy93aWtpcGVk/aWEvY29tbW9ucy8x/LzFkL1ZpbGxhX2Qn/RXN0ZV8wMS5qcGc",
      dailyRent: "200",
    },
    {
      id: 6,
      name: "Aphrodite",
      location: "Greece",
      category: "Seaside",
      guests: 12,
      bedrooms: 6,
      bathrooms: 6,
      squareMeter: "500",
      rating: 4.9,
      image: "https://imgs.search.brave.com/cAEaCvVAGqGrZJCIxdFHPf0qsx9aZwXPCO097qvbKmE/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5jbnRyYXZlbGVy/LmNvbS9waG90b3Mv/NjRhZGJhMzIzM2Uz/MzYxMjAxYjU0YTZj/L21hc3Rlci93XzMy/MCxjX2xpbWl0L1Nl/cmF5bmEtanVsMjMt/cHIuanBlZw",
      dailyRent: "320",
    },
    {
      id: 7,
      name: "Villa Sunset",
      location: "Italy",
      category: "Mountains",
      guests: 15,
      bedrooms: 8,
      bathrooms: 10,
      squareMeter: "1000",
      rating: 4.8,
      image: "https://imgs.search.brave.com/H8v4ZlK5LDaXsBAkOjENpEHJoiHru9jE-1x5xIXZuB8/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5jbnRyYXZlbGVy/LmNvbS9waG90b3Mv/NjNlZDYzNDczZWNh/NTY3NmNjN2FmNjU0/L21hc3Rlci93XzMy/MCxjX2xpbWl0L1Zp/bGxhJTIwU2FuJTIw/QmFyYmVyaW5vLWph/bjIzLXByLmpwZWc",
      dailyRent: "280",
    },
    {
      id: 8,
      name: "White Lady",
      location: "Italy",
      category: "Seaside",
      guests: 25,
      bedrooms: 25,
      bathrooms: 25,
      squareMeter: "1500",
      rating: 5.0,
      image: "https://imgs.search.brave.com/9c9KX5Qjf1KcdMKL2HD7aUMok_bHQfnSCaGV4H2MHX4/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly93d3cu/aXN1bGF0cmF2ZWwu/Y29tL3NpdGVzL2lz/dWxhdHJhdmVsLmNv/bS9maWxlcy9zdHls/ZXMvNDUweDMwMC9w/dWJsaWMvcHJvcGVy/dHkvMzI2NDAxL3Zp/bGxhLWxpdmlhXzEu/anBnP2l0b2s9LUN0/ekIxSkw",
      dailyRent: "400",
    },
    {
      id: 9,
      name: "Thebes",
      location: "Greece",
      category: "Seaside",
      guests: 5,
      bedrooms: 6,
      bathrooms: 6,
      squareMeter: "240",
      rating: 3.8,
      image: "https://imgs.search.brave.com/AM-4TOXnJBGD-6E0s3B8p2RW_Yjmo7FtwacwoLM3qOc/rs:fit:500:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5jbnRyYXZlbGxl/ci5jb20vcGhvdG9z/LzY0YWJjMGI5ODc2/MDYzZGRhNjE1M2Jh/MS9tYXN0ZXIvd18z/MjAsY19saW1pdC9T/ZXJheW5hLWp1bDIz/LXByLmpwZWc",
      dailyRent: "180",
    },
  ];